namespace VorpCharacter.Enums
{
    public enum ePedFaceFeature : uint
    {
        FaceSize = 0x84D6,
        EyebrowHeight = 0x3303,
        EyebrowWidth = 0x2FF9,
        EyebrowDepth = 0x4AD1,
        EarsHeight = 0xC04F,
        EarsAngle = 0xB6CE,
        EarsSize = 0x2844,
        EarsLobeSize = 0xED30,
        EyelidsHeight = 0x8B2B,
        EyelidsWidth = 0x1B6B,
        EyeDepth = 0xEE44,
        EyeAngle = 0xD266,
        EyeSeparation = 0xA54E,
        EyeHeight = 0xDDFB,
        NoseWidth = 0x6E7F,
        NoseSize = 0x3471,
        NoseHeight = 0x03F5,
        NoseAngle = 0x34B1,
        NoseCurvature = 0xF156,
        NostrilsSeparation = 0x561E,
        CheekbonesHeight = 0x6A0B,
        CheekbonesWidth = 0xABCF,
        CheekbonesDepth = 0x358D,
        MouthWidth = 0xF065,
        MouthDepth = 0xAA69,
        MouthDeviation = 0x7AC3,
        MouthHeight = 0x410D,
        UpperLipHeight = 0x1A00,
        UpperLipWidth = 0x91C1,
        UpperLipDepth = 0xC375,
        LowerLipHeight = 0xBB4D,
        LowerLipWidth = 0xB0B0,
        LowerLipDepth = 0x5D16,
        MandibleHeight = 0x8D0A,
        MandibleWidth = 0xEBAE,
        MandibleDepth = 0x1DF6,
        ChinHeight = 0x3C0F,
        ChinWidth = 0xC3B2,
        ChinDepth = 0xE323,
    }
}
